import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../sass/main.scss";
// import "../app/globals.css";

import { getGlobalSettings } from "@/data/loaders";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  const { data } = await getGlobalSettings()
  console.dir(data, { depth: null })
  if (!data) throw new Error("Failed to fetch global settings")
  return { header: data?.header, footer: data?.footer  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { header, footer } = await loader()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header data={header} />
        {children}
        <Footer data={footer} />
      </body>
    </html>
  );
}

/*/////// TODO NOTES //////////////////////////////////////////////////////////

KEEP IN MIND -------------------------

- Headline
  - Heading
  - Subheading


GENERAL -------------------------

- Continue Building out Info Section
  - More CTA (Link to Zillow & "Contact Us" - Brings to section ID)
  - Add background image option
  - Add "Highlights" (11+ Years in Business / 20+ Sales / 5 Star Rating)
  - Flush out "Theme" options

- Add "Aligntment" options to Services Section

- Build out Contact Section

- Add Metadata Somehow

- Standarize Font sizes / vars
- Standardize Colors / vars

- Replace SENJA Widget with custom Zillow Widget

- Really need to clean up "ContactForm / FormSection" naming conventions, it's a mess
  - BackgroundDarken is not hooked up to anything


BUGS ----------------------------

- Hero Section Form has weird (transition related?) bug
  - Scroll out of view, change viewport size, scroll back into view

- Form Validation Controls in Strapi (Required / customErrorMessage / etc.) do not work
  - Currently disabled (removed from all form fields). To reinstate, re-add "Field Validation Rules" to "Form Field Configuration".


CONCEPTS ------------------------

- Include Map of sold properties? Maybe have tabs between Sold/Listed?
  - (ALREADY SOMETHING SIMILAR ON ZILLOW PAGE !!!!) - Cannibalize API?


*//////////////////////////////////////////////////////////////////////////////